language: python

sudo: false
matrix:
  fast_finish: false
  include:
    - python: "2.7"
      env: TOXENV=py27
cache:
  directories:
    - $HOME/.cache/pip
    
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels silab
  - conda info -a
  - conda install --yes numpy pytables scipy matplotlib nose

install:
  - pip install ez_setup
  # - pip install -e git://pysparse.git.sourceforge.net/gitroot/pysparse/pysparse#egg=PySparse 
  - pip install -r requirements.txt -r requirements_tests.txt
script: nosetests
after_success: coveralls