language: python

sudo: false
matrix:
  fast_finish: false
  include:
    - python: "2.7.12"
      env: TOXENV=py27
cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install ez_setup
  # - pip install -e git://pysparse.git.sourceforge.net/gitroot/pysparse/pysparse#egg=PySparse 
  - pip install -r requirements.txt -r requirements_tests.txt
script: nosetests
after_success: coveralls